logging:
    path: ../logs
    file:
      max-size: 100MB
    level:
      root: INFO
      org.springframework.web: INFO
      com.xinyusoft.core.newuser: DEBUG
      com.xinyusoft.esb.helper.advisor: DEBUG
spring:
  redis:
    host: localhost
    port: 6379
    database: 10
  datasource:
    #url: jdbc:mysql://58.247.47.154:13306/testuser?useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/testuser?useSSL=false&serverTimezone=Asia/Shanghai
    username: xinyu
    password: abcd1234
    driver-class-title: com.mysql.cj.jdbc.Driver
    max-active: 4
    max-idle: 2
    min-idle: 2
    initial-size: 2

server:
  port: 8899
  servlet:
    context-path: /openapi
service:
  id: openapi
  name: openapi
registry:
  address: http://localhost:8888/rc/register



